server:
  port: ${PORT:8080}

spring:
  application:
    name: schedule-bot

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  liquibase:
    url: ${DB_URL}
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    change-log: db/changelog/changelog-master.yaml
    enabled: true

  jackson:
    time-zone: Europe/Samara

bot:
  name: ${BOT_NAME}
  token: ${BOT_TOKEN}

admin:
  id: ${ADMIN_ID}

scheduling:
  faculty:
    cron: "0 0 22 * * *" #Каждый день в 22:00
    enabled: false
  group:
    cron: "0 10 22 * * *" #Каждый день в 22:10
    enabled: false
  lesson:
    cron: "0 30 22 * * *" #Каждый день в 22:30
    enabled: false
  notification:
    cron: "0 0 23 * * *" #Каждый день в 23:00
    enabled: false

samara-university:
  semester-start-date: 2024-09-02
  faculty-url: https://ssau.ru/rasp
  group-url: https://ssau.ru/rasp/faculty/%d?course=%d
  lesson-url: https://ssau.ru/rasp?groupId=%d&selectedWeek=%d

integration:
  max-retries: 5
  retry-delay: 1000
  timeout: 5000


resilience4j:
  circuitbreaker:
    instances:
      samaraUniversityClientService:
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
        permittedNumberOfCallsInHalfOpenState: 3

  ratelimiter:
    instances:
      samaraUniversityClientService:
        limitForPeriod: 10
        limitRefreshPeriod: 1s
        timeoutDuration: 5s