server:
  port: ${PORT:8080}

spring:
  application:
    name: schedule-bot

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  liquibase:
    url: ${DB_URL}
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    change-log: db/changelog/changelog-master.yaml
    enabled: true


bot:
  name: ${BOT_NAME}
  token: ${BOT_TOKEN}

admin:
  id: ${ADMIN_ID}

scheduling:
  notification:
    delay: ${SCHEDULING_DELAY:86400000}
    enabled: false
  group:
    delay: ${SCHEDULING_DELAY:86400000}
    enabled: true
  faculty:
    delay: ${SCHEDULING_DELAY:86400000}
    enabled: false

samara-university:
  semester-start-date: 2024-09-02
  faculty-url: https://ssau.ru/rasp
  group-url: https://ssau.ru/rasp/faculty/%d?course=%d
  lesson-url: https://ssau.ru/rasp?groupId=%d&selectedWeek=%d

integration:
  max-retries: 5
  retry-delay: 1000

resilience4j:
  circuitbreaker:
    instances:
      samaraUniversityClientService:
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10000 # 10 секунд
        permittedNumberOfCallsInHalfOpenState: 3
