server:
  port: ${PORT:8080}

spring:
  application:
    name: schedule-bot

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: validate


  liquibase:
    change-log: db/changelog/changelog-master.xml
    enabled: true


bot:
  name: ${BOT_NAME}
  token: ${BOT_TOKEN}

admin:
  id: ${ADMIN_ID}

scheduling:
  notification:
    delay: ${SCHEDULING_DELAY:86400000}
    enabled: true
  group:
    delay: ${SCHEDULING_DELAY:86400000}
    enabled: false
  faculty:
    delay: ${SCHEDULING_DELAY:86400000}
    enabled: false

samara-university:
  semester-start-date: 2024-09-02
