server:
  port: ${PORT:8080}

spring:
  application:
    name: schedule-bot

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  liquibase:
    url: ${DB_URL}
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    change-log: db/changelog/changelog-master.yaml
    enabled: true

  jackson:
    time-zone: Europe/Samara

bot:
  name: ${BOT_NAME:ScheduleBot}
  token: ${BOT_TOKEN:5926617975:AAG8_WzhM6gE3ZdA3XCVJRSWTFBsNWuFx9M}

admin:
  id: ${ADMIN_ID:123}

scheduling:
  tomorrow-schedule-notification:
    cron: "0 20 22 * * *" #Каждый день в 22:20
    enabled: true
  schedule-difference-notification:
    cron: "0 0 * * * *" #Каждый час в :00 мин
    enabled: true
  parser:
    cron: "0 20 21 * * *" #Каждый день в 21:20
    enabled: true
  messages-sender:
    cron: "0 30 * * * *" #Каждый час в :30 мин
    enabled: true

samara-university:
  semester-start-date: 2024-09-02
  faculty-url: https://ssau.ru/rasp
  group-url: https://ssau.ru/rasp/faculty/%d?course=%d
  lesson-url: https://ssau.ru/rasp?groupId=%d&selectedWeek=%d

integration:
  max-retries: 5
  retry-delay: 1000
  timeout: 5000


resilience4j:
  circuitbreaker:
    instances:
      samaraUniversityClientService:
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
        permittedNumberOfCallsInHalfOpenState: 3

  ratelimiter:
    instances:
      samaraUniversityClientService:
        limitForPeriod: 10
        limitRefreshPeriod: 1s
        timeoutDuration: 5s